server:
  port: 8091

spring:
    application.name: gateway
    cloud:
      gateway:
        default-filters:
        - PrefixPath=/
        routes:
        - id: user
          uri: http://localhost:8085
          predicates:
          - Path=/user/**

        - id: skillcategory
          uri: http://localhost:8082
          predicates:
          - Path=/skill/** 
        
        - id: skillcategory
          uri: http://localhost:8082
          predicates:
          - Path=/category/** 
